# Generated by Django 6.0.2 on 2026-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('raca', models.CharField(choices=[('huma', 'Humà'), ('elfo', 'Elfo'), ('enano', 'Enano'), ('mediano', 'Mediano'), ('orco', 'Orco'), ('goblin', 'Goblin'), ('troll', 'Troll')])),
                ('classe', models.CharField(choices=[('guerrero', 'Guerrero'), ('mago', 'Mago'), ('picaro', 'Pícaro'), ('clerigo', 'Clérigo'), ('druida', 'Druida'), ('bardo', 'Bardo'), ('paladin', 'Paladín'), ('explorador', 'Explorador')])),
                ('nivell', models.IntegerField(default=1)),
                ('estadistiques', models.CharField(choices=[('força', 'Força'), ('destresa', 'Destresa'), ('constitucio', 'Constitució'), ('intel·ligencia', 'Intel·ligència'), ('sabiduria', 'Sabiduría'), ('carisma', 'Carisma')])),
            ],
        ),
    ]
