# Generated by Django 4.2.11 on 2026-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom del personatge', max_length=100)),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('classe', models.CharField(max_length=50)),
                ('nivell', models.IntegerField(default=1)),
                ('puntuacio_de_vida', models.IntegerField(verbose_name='HP')),
                ('força', models.IntegerField(default=10, verbose_name='FOR')),
                ('destresa', models.IntegerField(default=10, verbose_name='DES')),
                ('constitucio', models.IntegerField(default=10, verbose_name='CON')),
                ('intelligencia', models.IntegerField(default=10, verbose_name='INT')),
                ('saviesa', models.IntegerField(default=10, verbose_name='SAB')),
                ('carisma', models.IntegerField(default=10, verbose_name='CAR')),
                ('inventari', models.TextField(blank=True, help_text="Llista d'objectes que porta el personatge")),
            ],
        ),
    ]
