version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: cantina_apache
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./conf:/usr/local/apache2/conf/extra
      - ./logs:/usr/local/apache2/logs
      
      # Afegeix aquests nous volums:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./config/ssl/server.crt:/usr/local/apache2/conf/server.crt
      - ./config/ssl/server.key:/usr/local/apache2/conf/server.key
      - ./config/ssl/lacantina.crt:/etc/apache2/ssl/lacantina.crt
      - ./config/ssl/lacantina.key:/etc/apache2/ssl/lacantina.key

    restart: unless-stopped
