# Generated by Django 6.0 on 2026-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitoUno', models.FloatField()),
                ('digitoDos', models.FloatField()),
                ('operacion', models.CharField(max_length=10)),
                ('resultado', models.FloatField()),
            ],
        ),
    ]
