# Generated by Django 6.0.2 on 2026-02-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personatge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatge',
            name='raca',
            field=models.CharField(default='Humà', max_length=3),
        ),
    ]
