# Generated by Django 6.0.2 on 2026-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personatge', '0002_personatge_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatge',
            name='alineament',
            field=models.CharField(choices=[('caotic', 'Caòtic'), ('neutral', 'Neutral'), ('legal', 'Legal')], default='neutral', max_length=10),
        ),
    ]
