# Generated by Django 6.0.2 on 2026-02-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personatge', '0003_personatge_alineament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatge',
            name='raca',
            field=models.CharField(default='Humà', max_length=30),
        ),
    ]
